### PR TITLE
update to use the latest Alcor gateway schema

### PR DESCRIPTION
**Pull request by zhangml**
1. Update to use the latest Alcor gateway schema. #201 
2. This PR does not affect the existing testcases.
```
[==========] 47 tests from 10 test suites ran. (7281 ms total)
[  PASSED  ] 46 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ovs_l2_test_cases.1_port_CREATE_DELETE

 1 FAILED TEST
  YOU HAVE 14 DISABLED TESTS
```

```
[       OK ] zeta_programming_test_cases.DISABLED_zeta_scale_CHILD (120544 ms)
[----------] 1 test from zeta_programming_test_cases (120544 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (120544 ms total)
[  PASSED  ] 1 test.
```
```
[       OK ] ovs_l2_test_cases.DISABLED_2_ports_CREATE_test_traffic_PARENT (37601 ms)
[----------] 1 test from ovs_l2_test_cases (37601 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (37601 ms total)
[  PASSED  ] 1 test.
```
```
[       OK ] ovs_l3_test_cases.DISABLED_2_ports_ROUTING_test_traffic_PARENT (104080 ms)
[----------] 1 test from ovs_l3_test_cases (104080 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (104080 ms total)
[  PASSED  ] 1 test.
```
```
[       OK ] dhcp_request_test_case.DISABLED_l2_dhcp_test (14471 ms)
[----------] 1 test from dhcp_request_test_case (14471 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (14471 ms total)
[  PASSED  ] 1 test.
```
```
[       OK ] dhcp_request_test_case.DISABLED_l3_dhcp_test (14877 ms)
[----------] 1 test from dhcp_request_test_case (14877 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (14877 ms total)
[  PASSED  ] 1 test.
```
```
[       OK ] ovs_l3_test_cases.DISABLED_2_ports_ROUTING_test_traffic_one_machine (35942 ms)
[----------] 1 test from ovs_l3_test_cases (35942 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (35942 ms total)
[  PASSED  ] 1 test.
```
@er1cthe0ne The test results have been updated.

### CODE REVIEW

**Comment by zhangml** [comment]
@er1cthe0ne The update trigger method of gatewaystate has been rolled back.

**Comment by er1cthe0ne** [comment]
> @er1cthe0ne The update trigger method of gatewaystate has been rolled back.

Looking good. Please confirm the all the existing unit test is passing including the Zeta test cases.

**Comment by zhangml** [comment]
> > @er1cthe0ne The update trigger method of gatewaystate has been rolled back.
> 
> Looking good. Please confirm the all the existing unit test is passing including the Zeta test cases.

@er1cthe0ne The test results have been updated.

**Review by er1cthe0ne — APPROVED** [review]
Looks good. Thanks for sharing the test result and completing this task.

**Pull request merged**
